version: '3.9'
services:
  web:
    build: ./web
    ports:
      - "5001:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=mydb
    networks: 
      - mynetwork

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
